### ISSUE TITLE
Meaning of duplicate entries in curr_simplemaprefset_f?  One 

### ISSUE THREAD

**Issue by mgurley** [rorydavidson/SNOMED-CT-Database#11]
Thanks for this project.  Tremendously helpful.  This is not an issue with the project but more a question about how to interpret data in the SNOMED model.  I loaded the S Edition of SNOMED CT(R): March 2017 Release into the schema on PostgreSQL.  In the curr_simplemaprefset_f table I have some examples where the same mapping is present  with active=0 in one row and active=1 in another row.  With different values in the effectivetime column.  For example:

id | effectivetime | active | moduleid | refsetid  | referencedcomponentid |  maptarget
-- | ------------- | ------ | -------- | --------- | --------------------- |  --------
53be7b87-2f7f-5626-a10c-0221bca098f1| 20020731 | 1 | 900000000000207008 | 446608001 | 275990002 | C66.9
53be7b87-2f7f-5626-a10c-0221bca098f1 | 20080131 | 0| 900000000000207008 | 446608001 | 275990002 | C66.9

Does this mean that this mapping was active beginning "20020731" but then became inactive "20080131"?

**Comment by rorydavidson** [comment]
Thanks!
Yes, that's the correct interpretation. The SNOMED CT component with the most recent effective time is the relevant one which represents the current state of the component.
