### ISSUE TITLE
Import into Neo4j possible artefacts

### ISSUE THREAD

**Issue by KeremTubluk** [rorydavidson/SNOMED-CT-Database#22]
This may not be a bug but i suspect that it is, when importing Snomed-CT using the Snomed-CT tool some nodes get strange relationships. For example the concept 277644009 is related to 90433002 through an ISA relationship, but the concept 90433002 is also related to 277644009 trough a separate ISA relationship.

[277644009]-ISA->[90433002], [277644009]<-ISA-[90433002]

The SnomedCT version i am using is 20180731T120000Z.

**Comment by rorydavidson** [comment]
@KeremTubluk Thanks, that is strange. I've updated the repo to include recent fixes for the Neo4j import. Please try again with the latest code.
