### ISSUE TITLE
Neo4J import 7-2019 release

### ISSUE THREAD

**Issue by mertenssander** [rorydavidson/SNOMED-CT-Database#26]
Hi Rory,

I wanted to give this a go for a demo involving visualization of patient cohorts - but quickly ran into issues.
Running an import stalls on 'FIND_ROLENAMES'. I am running python 3.7.4 and py2neo 3.1.2. The code is executed in a WSL console, and the script does connect to my local Neo4J desktop server.
I have tried python 2.7 & 3.6 without any luck, same results..
I understand this is very old code from a 3rd party - but perhaps you could help me or point me in the right direction!

Best regards, Sander

**Console output:**
rm /var/tmp/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z -R && mkdir /var/tmp/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z && python snomed_g_graphdb_build_tools.py db_build --release_type full --mode build --action create --rf2 /c/Users/[*****]/Documents/Snomed\ release/dir/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z/Full/ --release_type full --neopw snomed --output_dir /var/tmp/SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z
SNOMED_G bin directory [/c/Users/[*****]/Documents/development/SNOMED-CT-Database/NEO4J/]
sequence did not exist, primed
JOB_START
FIND_ROLENAMES
FAILED (steps: ['FIND_ROLENAMES'])

Build log: [build.log](https://github.com/rorydavidson/SNOMED-CT-Database/files/3685132/build.log)

**Comment by rorydavidson** [comment]
Thanks for the note. I'm not really best placed to help as my knowledge of Neo4J is limited! However, if you add the issue to the equivalent repo with SNOMED International - https://github.com/IHTSDO/snomed-database-loader - and the original contributor should answer.

**Comment by mertenssander** [comment]
Hi Rory,
Thanks, I have opened an issue there; https://github.com/IHTSDO/snomed-database-loader/issues/34 .
Thanks!
