### ISSUE TITLE
issue about "sequence did not exist, primed"

### ISSUE THREAD

**Issue by aushikun** [rorydavidson/SNOMED-CT-Database#28]
Hello,

I am trying SNOMED_G tool, encountered the issue as below:
=======================
python ./prog/snomed_g_graphdb_build_tools.py db_build --action create --rf2 ./SCT_RF2_201801/ --release_type full --release_type full --neopw64 1234 --output_dir ./output/ --language_code 'en-us' --language_name 'USEnglish'
SNOMED_G bin directory [/Users/wangzhi/Program-test/Neo4j/Snomed_Neo/prog/]
sequence did not exist, primed
JOB_START
FIND_ROLENAMES
FAILED (steps: ['FIND_ROLENAMES'])
========================

I am using:
1. Python2.7 on a mac;
2.SNOMED CT of version 201801, full

I don't know how to solve this problem. Is there anyone who can help me? :)

**Comment by rorydavidson** [comment]
Hi, could you please add you issue to this repo, https://github.com/IHTSDO/snomed-database-loader, which is now the master for this one. (I'll switch it over one day!).
Someone there will be able to answer your question about the Neo4J imports.

**Comment by aushikun** [comment]
Thanks Rory!
